### ISSUE TITLE
ActionCreator without payload 

### ISSUE THREAD

**Issue by mwawrysz** [piotrwitek/react-redux-typescript#4]
ActionCreator without payload - require payload anyway

ActionCreators.testAction.create => ...testAction(null) 

One change: 

```
export declare class ActionCreator<T, P> {
    readonly type: T;
    readonly payload: P;
    constructor(type: T);
    create: (payload: P) => { // payload => payload?
        type: T;
        payload: P;
    };
}
```

**Comment by piotrwitek** [comment]
@mwawrysz unfortunately it will not work because then payload would be optional, not desirable
can be easily fixed by overloading function interface as in this example: https://github.com/piotrwitek/react-redux-typescript/blob/master/src/create-action-creator.ts

I was testing different other approaches for action creators, that are more idiomatic and better to maintain, I'll update this repo with v3.0 API as soon as I feel it covers all common use cases. 
You can check linked v3.0 creator proposal as inspiration if you want to cover empty payload creators.

**Comment by goldenbearkin** [comment]
what is blocking the v3.0 API? I am also looking for the empty payload creators.

**Comment by goldenbearkin** [comment]
just realized that the createActionCreator can be found in react-redux-typescript but not included in index.d.ts. is it intentable to hide createActionCreator? I found the createActionCreator is awesome which reduce lots of boilerplate. Do you not recommend people start using it?

**Comment by piotrwitek** [comment]
I was suppose to publish it as official but needed to do some real project testing first to become solid it's good enough, that's why it was hidden, I'll try to push it this week probably

**Comment by gsbelarus** [comment]
Are there any updates on v3 state?

**Comment by piotrwitek** [comment]
@gsbelarus yes I was working on it during this weekend, I'm certain it will be finished latest on friday, but probably even sooner.
I completed the hardest stuff which is type soundness of Action Creator method, now I need to update the documentation and add a few tests.

**Comment by leonth** [comment]
hi, any updates on this? If not would you take the existing implementation and export it (like this fork https://github.com/jervtub/react-redux-typescript)?

**Comment by piotrwitek** [comment]
@leonth I have finished a new API version which will be released today afternoon in beta as a separate library, and will be re-exported in this lib as well. (Finalizing examples section and documentation)

Basically it means:
- react-redux-typescript - will become Utility belt for React + Redux + TypeScript Projects
- ts-redux-actions - Typed Redux Actions for TypeScript (https://github.com/piotrwitek/ts-redux-actions)
